wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.16.6
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1714064592.0
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.9
      5: 0.16.6
      8:
      - 1
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 16
dropout:
  desc: null
  value: 0.6
epochs:
  desc: null
  value: 30
learning_rate:
  desc: null
  value: 0.0005
optimizer:
  desc: null
  value: sgd
